In [71]:
import pandas as pd
from pathlib import Path

In [72]:
# Define the directory path
directory_path = Path('../evaluation')

# Initialize an empty DataFrame to store the concatenated data
concatenated_df = pd.DataFrame()

In [73]:
# Loop through each CSV file in the directory
for csv_file in directory_path.glob('*.csv'):
    # Read the CSV file into a DataFrame
    current_df = pd.read_csv(csv_file)
    if 'l0_only' in csv_file.name:print(current_df)
    # Concatenate the current DataFrame with the previous ones
    concatenated_df = pd.concat([concatenated_df, current_df], ignore_index=True)
    #print(current_df['Unnamed: 0'])
concatenated_df.rename(columns={'Unnamed: 0': 'attack'}, inplace=True)
concatenated_df

     Unnamed: 0  rob  transfer-rob    duration
0  BB0-0.01-1.3  0.0      0.796296  951.047512
      Unnamed: 0  rob  transfer-rob     duration
0  BB0-0.001-1.3  0.0      0.777778  1096.112716
     Unnamed: 0  rob  transfer-rob    duration
0  BB0-0.01-3.0  0.0      0.722222  677.381547
     Unnamed: 0  rob  transfer-rob    duration
0  BB0-0.01-2.0  0.0      0.814815  965.752025
     Unnamed: 0  rob  transfer-rob    duration
0  BB0-0.01-1.1  0.0      0.777778  953.946284
     Unnamed: 0  rob  transfer-rob    duration
0  BB0-0.01-1.5  0.0      0.740741  957.185909
      Unnamed: 0  rob  transfer-rob     duration
0  BB0-0.001-1.1  0.0      0.759259  1117.984552
     Unnamed: 0  rob  transfer-rob    duration
0  BB0-0.01-5.0  0.0      0.722222  600.020261

           attack  rob  transfer-rob    duration
0      DF-20-0.02  0.0      0.814815         NaN
1       CW-10-0.1  0.0      0.666667         NaN
2         CW-20-1  0.0      0.537037   42.796458
3          CW-1-2  0.0      0.518519   46.482741
4       CW-50-0.2  0.0      0.666667         NaN
..            ...  ...           ...         ...
123  BB0-0.01-5.0  0.0      0.722222  600.020261
124    DF-100-0.2  0.0      0.814815    2.060993
125      CW-2-0.2  0.0      0.666667         NaN
126       CW-50-6  0.0      0.351852   53.460708
127     CW-20-0.0  0.0      0.666667         NaN

[128 rows x 4 columns]

In [75]:
def split_name(x):
    name, eps, conf = x.attack.split('-')
    conf = 0 if conf=='None' else float(conf)
    x['attack'] = name
    x['epsilon'] = float(eps)
    x['confidence'] = conf
    return x
res = concatenated_df.apply(split_name, axis=1)

res = res[['attack', 'epsilon', 'confidence', 'rob', 'transfer-rob']].sort_values(['attack', 'epsilon', 'confidence'], ascending=True)

In [76]:
res.reset_index(drop=True)

    attack   epsilon  confidence       rob  transfer-rob
0      BB0  0.001000         1.1  0.000000      0.759259
1      BB0  0.001000         1.3  0.000000      0.777778
2      BB0  0.010000         1.1  0.000000      0.777778
3      BB0  0.010000         1.3  0.000000      0.796296
4      BB0  0.010000         1.5  0.000000      0.740741
..     ...       ...         ...       ...           ...
123   FGSM  0.031373         0.0  0.074074      0.296296
124    PGD  0.003922         0.0  0.000000      0.092593
125    PGD  0.007843         0.0  0.000000      0.000000
126    PGD  0.015686         0.0  0.000000      0.000000
127    PGD  0.031373         0.0  0.000000      0.000000

[128 rows x 5 columns]

In [11]:
res.loc[res['transfer-rob']<0.5]

    attack     epsilon  confidence       rob  transfer-rob
129    BB0    0.000000         1.1  0.000000      0.388889
58     BB0    0.000000         2.0  0.000000      0.351852
49     BB0    0.000000         4.0  0.000000      0.388889
115    BB0   50.000000         1.1  0.000000      0.388889
57     BB0   50.000000         1.3  0.000000      0.333333
88     BB0   50.000000         1.5  0.000000      0.370370
130    BB0   50.000000         2.0  0.000000      0.370370
46     BB0   50.000000         4.0  0.000000      0.407407
31     BB0  100.000000         1.1  0.000000      0.388889
67     BB0  100.000000         1.3  0.000000      0.370370
25     BB0  100.000000         1.5  0.000000      0.351852
53     BB0  100.000000         2.0  0.000000      0.351852
11      CW    1.000000         4.0  0.000000      0.425926
86      CW    1.000000         6.0  0.000000      0.351852
28      CW    2.000000         4.0  0.000000      0.425926
82      CW    2.000000         6.0  0.000000      0.351852
113     CW    5.000000         4.0  0.000000      0.425926
64      CW    5.000000         6.0  0.000000      0.351852
24      CW   10.000000         4.0  0.000000      0.425926
26      CW   10.000000         6.0  0.000000      0.351852
102     CW   20.000000         4.0  0.000000      0.425926
80      CW   20.000000         6.0  0.000000      0.351852
59      CW   50.000000         4.0  0.000000      0.425926
132     CW   50.000000         6.0  0.000000      0.351852
34      CW  100.000000         4.0  0.000000      0.425926
13      CW  100.000000         6.0  0.000000      0.351852
84    FGSM    0.003922         0.0  0.018519      0.203704
5     FGSM    0.007843         0.0  0.000000      0.129630
126   FGSM    0.015686         0.0  0.018519      0.222222
111   FGSM    0.031373         0.0  0.074074      0.296296
99     PGD    0.003922         0.0  0.000000      0.092593
94     PGD    0.007843         0.0  0.000000      0.000000
87     PGD    0.015686         0.0  0.000000      0.000000
90     PGD    0.031373         0.0  0.000000      0.000000

In [37]:
df = res.loc[res['attack']=='DF']
df

    attack  epsilon  confidence  rob  transfer-rob
118     DF      1.0        0.02  0.0      0.814815
92      DF      1.0        0.04  0.0      0.814815
57      DF      1.0        0.08  0.0      0.814815
71      DF      1.0        0.20  0.0      0.814815
107     DF      1.0        0.40  0.0      0.777778
37      DF      1.0        0.80  0.0      0.722222
52      DF      2.0        0.02  0.0      0.814815
61      DF      2.0        0.04  0.0      0.814815
123     DF      2.0        0.08  0.0      0.814815
97      DF      2.0        0.20  0.0      0.814815
111     DF      2.0        0.40  0.0      0.777778
66      DF      2.0        0.80  0.0      0.722222
98      DF      5.0        0.02  0.0      0.814815
76      DF      5.0        0.04  0.0      0.814815
88      DF      5.0        0.08  0.0      0.814815
74      DF      5.0        0.20  0.0      0.814815
24      DF      5.0        0.40  0.0      0.777778
75      DF      5.0        0.80  0.0      0.722222
95      DF     10.0        0.02  0.0      0.814815
115     DF     10.0        0.04  0.0      0.814815
125     DF     10.0        0.08  0.0      0.814815
132     DF     10.0        0.20  0.0      0.814815
85      DF     10.0        0.40  0.0      0.777778
14      DF     10.0        0.80  0.0      0.722222
0       DF     20.0        0.02  0.0      0.814815
41      DF     20.0        0.04  0.0      0.814815
68      DF     20.0        0.08  0.0      0.814815
33      DF     20.0        0.20  0.0      0.814815
9       DF     20.0        0.40  0.0      0.777778
82      DF     20.0        0.80  0.0      0.722222
21      DF     50.0        0.02  0.0      0.814815
45      DF     50.0        0.04  0.0      0.814815
18      DF     50.0        0.08  0.0      0.814815
44      DF     50.0        0.20  0.0      0.814815
22      DF     50.0        0.40  0.0      0.777778
112     DF     50.0        0.80  0.0      0.722222
79      DF    100.0        0.02  0.0      0.814815
25      DF    100.0        0.04  0.0      0.814815
120     DF    100.0        0.08  0.0      0.814815
134     DF    100.0        0.20  0.0      0.814815
20      DF    100.0        0.40  0.0      0.777778
23      DF    100.0        0.80  0.0      0.722222

In [54]:
df = res.loc[res['attack']=='DF']
df = df.drop_duplicates('confidence')
df.sort_values('transfer-rob').head(55)
df.to_latex('./tables/DF.tex', index=False)
df

    attack  epsilon  confidence  rob  transfer-rob
113     DF      1.0        0.02  0.0      0.814815
85      DF      1.0        0.04  0.0      0.814815
52      DF      1.0        0.08  0.0      0.814815
65      DF      1.0        0.20  0.0      0.814815
103     DF      1.0        0.40  0.0      0.777778
33      DF      1.0        0.80  0.0      0.722222

In [77]:
df = res.loc[res['attack']=='BB0']
#df = df.drop_duplicates('confidence')
df.sort_values('transfer-rob').head(55)
df.to_latex('./tables/BB.tex', index=False)
df

    attack  epsilon  confidence  rob  transfer-rob
108    BB0    0.001         1.1  0.0      0.759259
33     BB0    0.001         1.3  0.0      0.777778
97     BB0    0.010         1.1  0.0      0.777778
19     BB0    0.010         1.3  0.0      0.796296
104    BB0    0.010         1.5  0.0      0.740741
84     BB0    0.010         2.0  0.0      0.814815
36     BB0    0.010         3.0  0.0      0.722222
123    BB0    0.010         5.0  0.0      0.722222

In [ ]:
best = list()
for eps in df.epsilon.unique():
    df = res.loc[res['attack']=='CW']
    best.append(df[df.epsilon==eps].sort_values('transfer-rob').iloc[0])
pd.DataFrame(best)

In [26]:
attack='PGD'
df = res.loc[res.attack==attack]
df

   attack   epsilon  confidence  rob  transfer-rob
99    PGD  0.003922         0.0  0.0      0.092593
94    PGD  0.007843         0.0  0.0      0.000000
87    PGD  0.015686         0.0  0.0      0.000000
90    PGD  0.031373         0.0  0.0      0.000000

In [38]:
attack='PGD'
df = res.loc[res.attack==attack]
df.rob = df.rob.astype(float).round(3)
df['transfer-rob'] = df['transfer-rob'].astype(float).round(3)
df['epsilon'] = (df.epsilon * 255).astype(int)
df.to_latex('./tables/pgd.tex', index=False)
df

/tmp/ipykernel_919481/33728323.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rob = df.rob.astype(float).round(3)
/tmp/ipykernel_919481/33728323.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['transfer-rob'] = df['transfer-rob'].astype(float).round(3)
/tmp/ipykernel_919481/33728323.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['epsilon'] = (df.epsilon * 255).astype(int)

   attack  epsilon  confidence  rob  transfer-rob
99    PGD        1         0.0  0.0         0.093
94    PGD        2         0.0  0.0         0.000
87    PGD        4         0.0  0.0         0.000
90    PGD        8         0.0  0.0         0.000

In [20]:
df.iloc[3:][['attack','epsilon','rob','transfer-rob']].to_latex('./tables/PGD.tex',index=False)

In [10]:
df.to_latex

    attack  epsilon  confidence  rob  transfer-rob
116    PGD    0.125         0.0  0.0           0.0
131    PGD    0.250         0.0  0.0           0.0
12     PGD    0.500         0.0  0.0           0.0
80     PGD    1.000         0.0  0.0           0.0
89     PGD    2.000         0.0  0.0           0.0
63     PGD    4.000         0.0  0.0           0.0
100    PGD    8.000         0.0  0.0           0.0